//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_CONCENTRADO_LABORATORIO
    {
        public int ID_DG { get; set; }
        public System.DateTime FECHAREG { get; set; }
        public string DG_NOMBRE { get; set; }
        public string CRITERIOS { get; set; }
        public string HALLAZGOS { get; set; }
        public string RECOMENDACIONES { get; set; }
        public string ANFETAMINAS { get; set; }
        public string COCAINA { get; set; }
        public string MARIHUANA { get; set; }
        public string OPIACEOS { get; set; }
        public string METANFETAMINAS { get; set; }
        public string TOXICOLOGICO { get; set; }
        public decimal ERIT { get; set; }
        public decimal HB { get; set; }
        public decimal HCTO { get; set; }
        public double PLQ { get; set; }
        public decimal LEU { get; set; }
        public double GLUCOSA { get; set; }
        public double UREA { get; set; }
        public decimal NITROGENO { get; set; }
        public decimal CREATININA { get; set; }
        public decimal BUN_CREATININA { get; set; }
        public decimal ACIDOURICO { get; set; }
        public double COLESTEROL { get; set; }
        public double TRIGLICERIDOS { get; set; }
        public double HDL { get; set; }
        public decimal LDL { get; set; }
        public decimal VLDL { get; set; }
        public decimal ATEROGENICO { get; set; }
        public double AST_TGO { get; set; }
        public double ALT_TGP { get; set; }
        public decimal BILIRRUBINA { get; set; }
        public decimal CALCIO { get; set; }
    }
}
