//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_REPORTE_FACT
    {
        public Nullable<int> AÑO { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURACION { get; set; }
        public string NO_FACT { get; set; }
        public string EST_FACTURA { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public decimal MONTO_PAGADO { get; set; }
        public Nullable<decimal> POR_COBRAR { get; set; }
        public Nullable<System.DateTime> FECHA_DE_PAGO { get; set; }
        public string UNIDAD_NEG { get; set; }
    }
}
