//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_CLIENTE_ASESOR
    {
        public string CODIGO { get; set; }
        public string CLIENTE { get; set; }
        public string ID_ASESOR { get; set; }
        public string ASESOR { get; set; }
    }
}
