//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_PEDIDOS_aMI
    {
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public decimal c4 { get; set; }
        public decimal c5 { get; set; }
        public string c6 { get; set; }
        public decimal NoPartida { get; set; }
        public string c12 { get; set; }
        public string iddoc { get; set; }
        public int tipodoc { get; set; }
        public string cseriedo01 { get; set; }
        public Nullable<System.DateTime> cFecha { get; set; }
        public Nullable<int> cFolio { get; set; }
        public string ccodigoc01 { get; set; }
        public string cliente { get; set; }
        public string cod_prod { get; set; }
        public string clave_producto { get; set; }
        public decimal cprecio { get; set; }
        public double cantidad { get; set; }
        public double surtidas { get; set; }
        public double pendientes { get; set; }
        public int TotalPM { get; set; }
        public Nullable<int> ao { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> dia { get; set; }
        public Nullable<int> diastrans { get; set; }
        public string RANGO_DIAS { get; set; }
        public int cimpreso { get; set; }
        public string ESTATUS_DOCUM { get; set; }
        public string cusaclie01 { get; set; }
        public int cunidade01 { get; set; }
        public string codigoAgente { get; set; }
        public string id_prod { get; set; }
        public string nombre_prod { get; set; }
        public string est_ped { get; set; }
        public System.DateTime fechaModificacion { get; set; }
        public decimal cidmovim01 { get; set; }
        public string comentarioPed { get; set; }
        public string referencia { get; set; }
        public string USUARIO_PED { get; set; }
        public string hora { get; set; }
        public string minuto { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
    }
}
