//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_PEDIDOSPDTES
    {
        public Nullable<System.DateTime> cFecha { get; set; }
        public Nullable<int> cFolio { get; set; }
        public string cliente { get; set; }
        public string cod_prod { get; set; }
        public string RANGO_DIAS { get; set; }
        public decimal cprecio { get; set; }
        public double cantidad { get; set; }
        public double pendientes { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> dia { get; set; }
        public string ESTATUS_DOCUM { get; set; }
        public string nombre_prod { get; set; }
        public string est_ped { get; set; }
        public string referencia { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public string AGENTE { get; set; }
    }
}
