//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_PAPELETAS_ORDEN
    {
        public int folio { get; set; }
        public string empresa { get; set; }
        public string SEXO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_ALTA { get; set; }
    }
}
