//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_PERFILESONLINE
    {
        public System.DateTime fecha_alta { get; set; }
        public byte cd_estatus { get; set; }
        public string id_empresa { get; set; }
        public string empresa { get; set; }
        public string perfil { get; set; }
        public string id_perfil { get; set; }
        public string ESTATUS { get; set; }
        public string PERF_DESCRIPCION { get; set; }
        public string CONTACTO { get; set; }
        public string TIEMPO_ENTREGA_ELECT { get; set; }
        public string TIEMPO_ENTREGA_FISICO { get; set; }
        public string GENERO { get; set; }
        public string PUESTO_PACIENTE { get; set; }
        public string ENTREGA_DE_EXP { get; set; }
        public string EMPRESA2 { get; set; }
        public string PROYECTO { get; set; }
        public string EMAIL { get; set; }
        public string EMAIL2 { get; set; }
        public string EMAIL3 { get; set; }
        public string TELEFONO { get; set; }
        public string EXTENSION { get; set; }
        public string TIPO_EXAMEN { get; set; }
        public string FORMATO_REPORTE { get; set; }
        public string COMENTARIOS { get; set; }
        public string ID_EXAMEN { get; set; }
        public string NOMBRE_EXAMEN { get; set; }
        public string ID_ASESOR { get; set; }
        public string ASESOR { get; set; }
    }
}
