//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_PAPELETADIA_CEM3
    {
        public int FOLIO { get; set; }
        public string RFC { get; set; }
        public string ID_EMPRESA { get; set; }
        public string NOMBREYID { get; set; }
        public string EMPRESA { get; set; }
        public string ID_PERFIL { get; set; }
        public string PERF_DESCRIPCION { get; set; }
        public string NOMBRE_PACIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string COMENTARIOS { get; set; }
        public string SEXO { get; set; }
        public string FECHA_ALTA { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> DIA { get; set; }
        public string NOMBRE_EXAMEN { get; set; }
        public int EX_REALIZADO { get; set; }
        public string ESTATUS { get; set; }
        public string COMENTARIOS_PAP { get; set; }
        public string OFNA { get; set; }
        public string SERVICIO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public string est_pap { get; set; }
        public Nullable<int> IDMODULOORIGEN { get; set; }
        public string ID_ASESOR { get; set; }
        public string ASESOR { get; set; }
    }
}
