//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_CLIENTES_CONTPAQDOM
    {
        public string ID_CTE { get; set; }
        public string NOMBRE { get; set; }
        public string CRFC { get; set; }
        public string ID_AGENTE { get; set; }
        public string ASESOR { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string CNOMBRECALLE { get; set; }
        public string CNUMEROEXTERIOR { get; set; }
        public string CNUMEROINTERIOR { get; set; }
        public string CCODIGOPOSTAL { get; set; }
        public string CCOLONIA { get; set; }
        public string CCIUDAD { get; set; }
        public string CESTADO { get; set; }
        public string CUSOCFDI { get; set; }
        public string CREGIMFISC { get; set; }
        public string REGIMEN { get; set; }
        public string USOCFDI { get; set; }
    }
}
