//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_TRELLEBORG_ADUIOMETRIA
    {
        public int FOLIO { get; set; }
        public string NOMBRE_PACIENTE { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string EMPRESA { get; set; }
        public string AUD_FARINGE { get; set; }
        public string AUD_CAD { get; set; }
        public string AUD_MTD { get; set; }
        public string AUD_MTI { get; set; }
        public string AUD_DESCRIPCION { get; set; }
        public string AUD_DESCRIPCION2 { get; set; }
        public Nullable<int> aud_od_500HZ { get; set; }
        public Nullable<int> AUD_OD_1000HZ { get; set; }
        public Nullable<int> AUD_OD_2000HZ { get; set; }
        public Nullable<int> AUD_OD_3000HZ { get; set; }
        public Nullable<int> aud_II_500HZ { get; set; }
        public Nullable<int> AUD_II_1000HZ { get; set; }
        public Nullable<int> AUD_II_2000HZ { get; set; }
        public Nullable<int> AUD_II_3000HZ { get; set; }
        public string OD_NOSOL { get; set; }
        public Nullable<decimal> AUD_OD_PERDIDA { get; set; }
        public Nullable<decimal> AUD_OI_PERDIDA { get; set; }
        public Nullable<decimal> AUD_HIPO_BIL_COMB { get; set; }
        public string OD_ETIO { get; set; }
        public string OI_NOSOL { get; set; }
        public string OI_ETIO { get; set; }
        public string DIAGOD { get; set; }
        public string COMENTOD { get; set; }
        public string DIAGOI { get; set; }
        public string COMENTOI { get; set; }
    }
}
