//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_PAPELETA_DESVIO_ONLINE
    {
        public int PAPELETA { get; set; }
        public string PERFIL { get; set; }
        public string NOMBRE_PACIENTE { get; set; }
        public string COMENTARIOS { get; set; }
        public string PLAZA { get; set; }
        public string ID_EMPRESA { get; set; }
        public string EMPRESA { get; set; }
    }
}
