//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_CIFRAS_AMIHIST
    {
        public string MOV { get; set; }
        public string DOC { get; set; }
        public string FOLIO { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> ALMACEN { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> AÑO { get; set; }
        public Nullable<int> DIA { get; set; }
        public string CVE_AGENTE { get; set; }
        public string NB_AGENTE { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public string ID_CTE { get; set; }
        public string NB_CTE { get; set; }
        public string ESTATUS { get; set; }
        public string RAZON_SOCIAL { get; set; }
    }
}
