//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_FACTURAS_ORIGEN
    {
        public string FOLIOFACT { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string COMENTARIOS { get; set; }
        public string COMENTARIOS2 { get; set; }
        public string REFERENCIA { get; set; }
        public string ID_CLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public string FOLIOPED { get; set; }
        public string ESTATUS { get; set; }
        public string ID_ASE { get; set; }
        public string ASESOR { get; set; }
        public string USER_FACT { get; set; }
    }
}
