//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_REG_PAPELETADIA
    {
        public System.DateTime FECHA_ALTA { get; set; }
        public int FOLIO { get; set; }
        public string RFC { get; set; }
        public string Nombre { get; set; }
        public string MATERNO { get; set; }
        public string PATERNO { get; set; }
        public string ID_EMPRESA { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string ID_PERFIL { get; set; }
        public Nullable<int> Edad { get; set; }
        public string PLAZA { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> DIA { get; set; }
        public Nullable<int> AÑO { get; set; }
        public Nullable<int> IDMODULOORIGEN { get; set; }
        public string Telefono { get; set; }
    }
}
