//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_CG_CONTPASAT
    {
        public string CESTADO { get; set; }
        public string VERSION { get; set; }
        public int CIDCPTODOC { get; set; }
        public string CNOMBRECONCEPTO { get; set; }
        public System.DateTime CFECHAEMI { get; set; }
        public double CFOLIO { get; set; }
        public int CIDFOLDIG { get; set; }
        public string RFCRECEPTOR { get; set; }
        public string NOMBRE_RECEPTOR { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string MONEDA { get; set; }
        public string CMETODOPAG { get; set; }
        public string METODOPAGO { get; set; }
        public string FORMAPAGO { get; set; }
        public string UUID { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string XML { get; set; }
    }
}
