//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_FM_PAPSA_CAT_TOTALES
    {
        public int FOLIO { get; set; }
        public string EMPRESA { get; set; }
        public string NOMBRE_PACIENTE { get; set; }
        public string NOMBRE_EXAMEN { get; set; }
        public Nullable<byte> ASHC_ID_APTITUD_HALLAZGOS { get; set; }
        public string ASHC_RECOMENDACIONES { get; set; }
        public string CAT_APTITUD_HALLAZGOS { get; set; }
    }
}
