//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TU_FM_PRODUCSIM
    {
        public string ID_EXAMEN { get; set; }
        public string NOMBRE_EXAMEN { get; set; }
        public string ID_PANTALLA_EXAMEN { get; set; }
    }
}
