//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CORTE_TOYOTA
    {
        public int ID_DG { get; set; }
        public System.DateTime FECHAREG { get; set; }
        public string DG_NOMBRE { get; set; }
        public int toxicologico { get; set; }
        public Nullable<decimal> DOP5 { get; set; }
        public int examen_medico { get; set; }
        public Nullable<decimal> EM { get; set; }
        public int audiometria { get; set; }
        public Nullable<decimal> AUD { get; set; }
        public int espirometria { get; set; }
        public Nullable<decimal> ESP { get; set; }
        public int radiografias { get; set; }
        public Nullable<decimal> RXCOL { get; set; }
        public int perfil_Bioq { get; set; }
        public Nullable<decimal> PERFILBIOQ { get; set; }
        public string mes_corte { get; set; }
    }
}
