//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CG_FACTURAS
    {
        public string rango { get; set; }
        public Nullable<int> orden_rango { get; set; }
        public string ID_KEPLER { get; set; }
        public string TP_FOLIO { get; set; }
        public string SUCURSAL { get; set; }
        public string TP_UNIDADNEGOCIO { get; set; }
        public string TP_DIASCREDITO { get; set; }
        public Nullable<int> TP_DIASTRANS { get; set; }
        public string ID_CTE { get; set; }
        public string NB_CTE { get; set; }
        public string CVE_AGENTE { get; set; }
        public string NB_AGENTE { get; set; }
        public string DOCUMENTO { get; set; }
        public string ESTATUS_DOC { get; set; }
        public Nullable<System.DateTime> FH_FACTURA { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> SUBTOTAL_PM { get; set; }
        public Nullable<decimal> DESCTO { get; set; }
        public Nullable<decimal> DESCTO_PM { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> IVA_PM { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> IMPORTE_PM { get; set; }
        public string MONEDA { get; set; }
        public Nullable<double> TIPO_CAMBIO { get; set; }
        public string REFERENCIA { get; set; }
        public System.DateTime FH_INSERCION { get; set; }
        public Nullable<System.DateTime> FH_MODIF { get; set; }
        public Nullable<System.DateTime> FH_ULT_ABONO { get; set; }
        public Nullable<System.DateTime> FH_ULT_ABONO_INS { get; set; }
        public string USUARIO_DOC { get; set; }
        public Nullable<System.DateTime> FH_DOC { get; set; }
        public Nullable<int> TC_RANGO { get; set; }
        public Nullable<int> CD_ESTATUS { get; set; }
        public Nullable<decimal> ABONO_MORIGEN { get; set; }
        public Nullable<decimal> ABONO_PM_CONSOL { get; set; }
        public Nullable<decimal> TOTAL_COMISION { get; set; }
        public string EST_COMISION { get; set; }
        public string RANGO_PAGO { get; set; }
        public Nullable<System.DateTime> FH_PAGO { get; set; }
        public Nullable<decimal> ABONO_PM_FHULTAB { get; set; }
        public string ACTFECHAPAGO { get; set; }
        public Nullable<decimal> ABONO_PM_CONSOL_TCF { get; set; }
        public string UNIDAD_NEGOCIO { get; set; }
    }
}
