//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportadoami.Models.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SEGUIMIENTO_PERFILES
    {
        public string id_cte { get; set; }
        public string nombre { get; set; }
        public string id_perfil { get; set; }
        public string perf_descripcion { get; set; }
        public string ESTATUS_PERFIL { get; set; }
        public string id_empresa { get; set; }
        public string empresa { get; set; }
        public string id_examen { get; set; }
        public string nombre_examen { get; set; }
    }
}
